# Exit the screensaver immediately on ordinary local input.
MOUSE_MOVE quit
MOUSE_BTN0 quit
MOUSE_BTN1 quit
MOUSE_BTN2 quit
MOUSE_BTN3 quit
MOUSE_BTN4 quit
MOUSE_BTN5 quit
MOUSE_BTN6 quit
MOUSE_BTN7 quit
WHEEL_UP quit
WHEEL_DOWN quit
WHEEL_LEFT quit
WHEEL_RIGHT quit
SPACE quit
ENTER quit
ESC quit
BS quit
DEL quit
INS quit
HOME quit
END quit
PGUP quit
PGDWN quit
UP quit
DOWN quit
LEFT quit
RIGHT quit
TAB quit
0 quit
1 quit
2 quit
3 quit
4 quit
5 quit
6 quit
7 quit
8 quit
9 quit
a quit
b quit
c quit
d quit
e quit
f quit
g quit
h quit
i quit
j quit
k quit
l quit
m quit
n quit
o quit
p quit
q quit
r quit
s quit
t quit
u quit
v quit
w quit
x quit
y quit
z quit
A quit
B quit
C quit
D quit
E quit
F quit
G quit
H quit
I quit
J quit
K quit
L quit
M quit
N quit
O quit
P quit
Q quit
R quit
S quit
T quit
U quit
V quit
W quit
X quit
Y quit
Z quit
F1 quit
F2 quit
F3 quit
F4 quit
F5 quit
F6 quit
F7 quit
F8 quit
F9 quit
F10 quit
F11 quit
F12 quit
KP0 quit
KP1 quit
KP2 quit
KP3 quit
KP4 quit
KP5 quit
KP6 quit
KP7 quit
KP8 quit
KP9 quit
KP_DEC quit
